### ISSUE TITLE
Mulan on JVM 11

### ISSUE THREAD

**Issue by arnaldocan** [tsoumakas/mulan#27]
Hello

I having trouble to run Mulan on JVM 11 as JAXB is not in the foundation classes anymore. I undersdant I need to add some jars to my class-path, and have tried some options (jakarta.xml.bind-api, javax.activation-api, jaxb-api, jaxb-core, jaxb-impl, jaxb-runtime), but without success.

This is the error I get when a try to run Mulan:

Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at mulan.data.MultiLabelInstances.loadLabelsMeta(MultiLabelInstances.java:574)
        at mulan.data.MultiLabelInstances.<init>(MultiLabelInstances.java:202)
       (...)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)

Thanks in advance

**Comment by Nanfeizhilu** [comment]
I think you need to create two new files in mulan\mulan\ folder:
The https://github.com/Nanfeizhilu/Files-for-Mulan-to-Avoid-NoClassDefFoundError shows how to do this

**Comment by arnaldocan** [comment]
Hi, thank's for the answer. I solved this issue by using JVM 8. 

I didn't test it, but it seems to me that the suggested fix is for other Mulan error. This one possibly has to do with the removal of Jaxb from the JVM and would require at least the insertion of a jar file in Mulan folder for libs.
