### ISSUE TITLE
im getting this error 

### ISSUE THREAD

**Issue by monisha08041998** [tsoumakas/mulan#28]
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at mulan.data.MultiLabelInstances.loadLabelsMeta(MultiLabelInstances.java:574)
	at mulan.data.MultiLabelInstances.<init>(MultiLabelInstances.java:202)
	at MulanExp2.main(MulanExp2.java:17)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at mulan.data.MultiLabelInstances.loadLabelsMeta(MultiLabelInstances.java:574)
	at mulan.data.MultiLabelInstances.<init>(MultiLabelInstances.java:202)
	at MulanExp2.main(MulanExp2.java:17)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:404)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:179)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:119)

**Comment by Nanfeizhilu** [comment]
I think you need to create two new files in mulan\mulan\ folder:
1.  create ".project" file and write following codes to it:
<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
	<name>mulan</name>
	<comment></comment>
	<projects>
	</projects>
	<buildSpec>
		<buildCommand>
			<name>org.eclipse.jdt.core.javabuilder</name>
			<arguments>
			</arguments>
		</buildCommand>
		<buildCommand>
			<name>org.eclipse.m2e.core.maven2Builder</name>
			<arguments>
			</arguments>
		</buildCommand>
	</buildSpec>
	<natures>
		<nature>org.eclipse.jdt.core.javanature</nature>
		<nature>org.eclipse.m2e.core.maven2Nature</nature>
	</natures>
</projectDescription>
2. create ".classpath" file and write following codes to it 
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" output="target/classes" path="src/main/java">
		<attributes>
			<attribute name="optional" value="true"/>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="target/test-classes" path="src/test/java">
		<attributes>
			<attribute name="optional" value="true"/>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8">
		<attributes>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="con" path="org.eclipse.m2e.MAVEN2_CLASSPATH_CONTAINER">
		<attributes>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="output" path="target/classes"/>
</classpath>

**Comment by Nanfeizhilu** [comment]
> Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
> at mulan.data.MultiLabelInstances.loadLabelsMeta(MultiLabelInstances.java:574)
> at mulan.data.MultiLabelInstances.(MultiLabelInstances.java:202)
> at MulanExp2.main(MulanExp2.java:17)
> Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
> at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
> at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
> at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
> at mulan.data.MultiLabelInstances.loadLabelsMeta(MultiLabelInstances.java:574)
> at mulan.data.MultiLabelInstances.(MultiLabelInstances.java:202)
> at MulanExp2.main(MulanExp2.java:17)
> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:404)
> at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:179)
> at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:119)
