### ISSUE TITLE
query about mulan/classifier/MultiLabelLearner : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by vaishalit** [tsoumakas/mulan#9]
[StartWeka java program.txt](https://github.com/tsoumakas/mulan/files/768258/StartWeka.java.program.txt)

Hi
 I am using Eclipse(Luna-r) on Windows 7 , 64 bit OS.  I am trying to run BinaryRelevance using Mulan 1.5 and Weka 3.7 using emotions dataset. But getting follwing error. Please help me to resolve this error.

Exception in thread "main" java.lang.UnsupportedClassVersionError: mulan/classifier/MultiLabelLearner : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.access$100(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
    at java.lang.Class.getMethod0(Unknown Source)
    at java.lang.Class.getMethod(Unknown Source)
    at sun.launcher.LauncherHelper.getMainMethod(Unknown Source)
    at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

**Comment by tsoumakas** [comment]
Hi,

It's most probably an issue of Java version. Have you tried with Java 8? 

See also: http://stackoverflow.com/questions/22489398/unsupported-major-minor-version-52-0

Best,

Greg
